#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path(File.join('..', 'lib'), __dir__).freeze
$LOAD_PATH.unshift lib unless $LOAD_PATH.include? lib

require 'yard/cov'
require 'yard/cov/cli'

YARD::Cov::CLI.run(*ARGV)
