#!/usr/bin/env ruby -U
# frozen_string_literal: true

lib = File.expand_path('lib', __dir__).freeze
$LOAD_PATH.unshift lib unless $LOAD_PATH.include? lib

require 'yard/cov'
require 'yard/cov/cli'

YARD::Cov::CLI.run(*ARGV)
